name: python-example

services:
  nginx:
    build:
      context: ../
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "127.0.0.1:${NGINX_PROXY_PORT:-80}:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../
      dockerfile: .docker/backend/Dockerfile
      target: runner
    command: sh -c "python -m main \"prod\""
    extra_hosts:
      - host:host-gateway
    environment:
      DATABASE_URL: ${BACKEND_DATABASE_URL:-postgresql://db:db@backend-db:5432/db?serverVersion=16&charset=utf8}
      JWT_SECRET: ${BACKEND_SECRET_KEY:-LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3FkMjV6RHpUNmMybzQKZFNDOHZYT0FXNFFKUGNzL1hneWFYMjlCOEMwanNpQ3cxSDE1dE1qRnczNkwyekxEZHltRW93N0VrSFNJc29BKwpBbDZnR2laVEg1ZGQ4OGRqa0hrS0VXbWZoS1RIYjBRV04yNEJJY2R0bHZvOGFMeUMwK1BocTgvVlhJa3huUVRCCncvRWhmZzJ0dHU4VzJqaFA2aktGUUdYRDRZRkdpdW1LNzNwNnIrUU1CODgvZ2xaWEowZjZaYW94anJPMGg0eGwKMzczazdjUTNseVNzb0MvS2t3V1QyWU9kbzhMWmxVSHFWQUx4SDBIbjJnYUpXSXhsdzc2Q2ZxVWp0K2ljdDVZZgptNlpidERxOERoNFAzQTErWVkrLzZQOTYxbEJOS2haY1hQSEIyNXpaVzkxTWpHRC9EM3Jkdk1xMElqeFNuVitHCnlhZEV3OXhmQWdNQkFBRUNnZ0VBUzJsZmJyNUUrU0VTMWh3VzJmaFR2dTU5YUZzeWJYdU5Sc08rWStTOUMyUVQKYXpidHRXaEJRNS9hL1VNQTM1RDVTSWljRVdBNGRYckdHZWlSZFBGc2oreFRXY2h0SmtJMUVidW5SdDcyeUpXVQpBT0lQbzZlT1lwQmVibGdGUVRrOHdFcHlQSmpkeHBtSWo3Ry9uRW40QWlnQitGR2NoTm45OUk0TEZ3OU5VZWVMCkhwWlVRdFROdE1kREduQldsamFjNWdVeTUyY2lJMTF2ZFFuNDBaYVlYU2ViQkc3YXZ3em9Mc3ZBbHJ5TUNqMisKNTBCOFJMaEViVzNUWnB1eGNFMTFQQkVFVnNMM0JSQU1BN1c5bjRlNzFpVG5jK1dldjlYVk9adUNLd2dZQm9xRwpBWEdqQUpKcTUyeXpYbHVmVVZIYUJNMk1NSFNuV1hYWVoxTndyWkdkWlFLQmdRRHFjbVNzYXhpcnhLa3lQbXh3CnRueWhaWXFKeFVUVW5hajNtbDBvc0NFdDU1ZUxLR0taKzJDWVo2ZWlSenkzdU4vUkt6YVI3QUVFb1RyK3RCcXkKbnl6TU1zVnllT25VNC9hbDk1QVZvQnA5R1d6ZkRjRWcrblhrWUk4VE13RTNIL2J0N21UZmZudWdET0w3QkJ3WAp0WE5tdHhrNERxazNZT1E2eGgvVXdzelgwd0tCZ1FDNkkwbmllRUFsN2Zuc1JLazZRS3ZBNG16dU9Fb0VTMFBuCjBveFJxNk1BMk5wVTZaenUxbDJRRHNMVDlkbmgzMEFhZVcwZUhWSUsrODJ4akU1WlVIMjB2WkxZb1lmcjFrRHcKakEzd0NqL2MyWlc0NkFWbVdJakhYUm9jaWphTFZqV3hFblI2OHNKS1orVUhraXdxck1Xa2NEK2k3YnFiKzRrdwprd09xaXltOXhRS0JnUUNxdWtVZjNobW9ORjEyTGtrdngyUjQ4QVgwRUFqd3dDTWt0RysweXBaTzVJRFNJTVcxCkZuOGdYUk9STkVrK0RVNUg5eTBWRklVbFJ2ZzhOUkhnRTlRK201WjNweCs1SFkwbkRXSUtyWDI4cmdBL2FyZkMKZVVIUzNwSXlUQWxOaUdSOG5nY3RUZUZmQ3lOYjRvRkdycWRzSEZnc0gxa1E3K2tqOTlXRVRadDRhd0tCZ0huagp5ZXBIbkpvNThFTkw0eFdHYS9KdlU2M2JwbnlSWFBKZDZnMUJQQWk5K0p0S0w3NG5HalhQdEwxZ2JVR0FGRlpCCjFiYTJ0SmNFdFhuaXl4dXBuZWZSakd2WHUwNHdpMjM2Q05aN243NWJyYlBjSEUwZEJOU29ud1M1YldacEdkZk8Kb2dBeElCSGhYeFZLSHlvQzRab0E5MnNXQ2ZGREVsK0FwaEh6OTIyUkFvR0JBTU5FSHVqYUxHUXdFSXEvSGVtSAoxSThyT3dtS2ZwT2hCaDd1VHRxNWlrMTNyTUFSOVNBVHh1RUpRSHhyeWNkVHY2dnkrV3F6M1gya1lJR0ZEc3g2Cm44TExRMjNqYTlYRnFaOXNwRmRaNGxBMjdkS2UzVmlpRENyQTNGMk5PYkN5ZXZscEIzbktVandUMHFqTDNyaTUKRjNLTXczcnFSZ1RYV0VmandRYmlIRjNjCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K}
      JWT_ALGORITHM: ${BACKEND_JWT_ALGORITHM:-HS256}
      JWT_DURATION_MIN: ${BACKEND_JWT_DURATION_MIN:-30}